#                                    Assignment 1.2
######                                                                                                                                                                 By
######                                                                                                                                                                 Shaina Mehta
######                                                                                                                                                                 7CSE 4Y
######                                                                                                                                                                 A2305219268

## Q1

### (1)

In [1]:
import pandas as pd
import numpy as np
d = {'Name':pd.Series(['Tom','James','Ricky','Vin','Steve','Smith','Jack']), 'Age':pd.Series([25,26,25,23,30,29,23]), 'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8])}

In [2]:
df = pd.DataFrame(d,columns=['Name','Age','Rating'])
df.head()

Name  Age  Rating
0    Tom   25    4.23
1  James   26    3.24
2  Ricky   25    3.98
3    Vin   23    2.56
4  Steve   30    3.20

In [3]:
df.tail()

Name  Age  Rating
2  Ricky   25    3.98
3    Vin   23    2.56
4  Steve   30    3.20
5  Smith   29    4.60
6   Jack   23    3.80

In [4]:
df.shape

(7, 3)

In [5]:
df.size

21

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    7 non-null      object 
 1   Age     7 non-null      int64  
 2   Rating  7 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 296.0+ bytes


### (2)

In [7]:
ipl_data = {'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings', 'kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'], 'Rank': [1, 2, 2, 3, 3,4 ,1 ,1,2 , 4,1,2], 'Year': [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017], 'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}
df = pd.DataFrame(ipl_data)
df

Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5    kings     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11  Riders     2  2017     690

In [8]:
a = df.groupby('Rank').get_group(1)
b = df.groupby('Rank').get_group(2)
c = df.groupby('Rank').get_group(3)
d = df.groupby('Rank').get_group(4)
e = c.merge(d,how='outer',on='Rank')

In [9]:
a

Team  Rank  Year  Points
0   Riders     1  2014     876
6    Kings     1  2016     756
7    Kings     1  2017     788
10  Royals     1  2015     804

In [10]:
b

Team  Rank  Year  Points
1   Riders     2  2015     789
2   Devils     2  2014     863
8   Riders     2  2016     694
11  Riders     2  2017     690

In [11]:
e

Team_x  Rank  Year_x  Points_x  Team_y  Year_y  Points_y
0  Devils     3  2015.0     673.0     NaN     NaN       NaN
1   Kings     3  2014.0     741.0     NaN     NaN       NaN
2     NaN     4     NaN       NaN   kings  2015.0     812.0
3     NaN     4     NaN       NaN  Royals  2014.0     701.0

## Q2

In [12]:
a = np.array([10,20,30]) 
b = np.array([3,5,7])

In [13]:
a

array([10, 20, 30])

In [14]:
b

array([3, 5, 7])

In [15]:
c = pow(a,b)
c

array([     1000,   3200000, 395163520], dtype=int32)

In [16]:
d = np.mod(a,b)
d

array([1, 0, 2], dtype=int32)

In [17]:
e = np.remainder(a,b)
e

array([1, 0, 2], dtype=int32)